### ISSUE TITLE
Браузер Edge. В селекторах и редакторах браузер добавляет "x" для очистки элемента

### ISSUE THREAD

**Issue by shevchuk-vadim** [alex-kukhtin/A2v10#107]
Это, в частности, очень некрасиво в редакторах фильтров, в которых уже есть свой "x" для сброса фильтра

**Comment by alex-kukhtin** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear

**Comment by alex-kukhtin** [comment]
Fixed in 7242
