### ISSUE TITLE
При загрузке не срабатывает асинхронный валидатор

### ISSUE THREAD

**Issue by shevchuk-vadim** [alex-kukhtin/A2v10#115]
Это приводит к тому, что при копировании элемента справочника он сохраняется без контроля дубликатов.

**Comment by alex-kukhtin** [comment]
Вообще-то так задумано. Он и не должен срабатывать. Представь, что у тебя сотня элементов.
Валидатор срабатывает при изменениях.
Подразумевается, что если уж в базу что-то записано, то оно правильное.
