### ISSUE TITLE
BindCmd Report

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#123]
Command="{BindCmd Report, Report='Invoice', Data={Bind Root.$ReportParams}, Export=True}"
Не работает передача параметров.
Пример: /home/cabinet/show/2 - Сформувати рахунок

**Comment by alex-kukhtin** [comment]
И еще - если нет аргумента, в url '/null' вместо '/0'

**Comment by alex-kukhtin** [comment]
done in 7460
