### ISSUE TITLE
Странное поведение атрибута CheckReadOnly=True

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#131]
Режим readonly в разделе "Персонал"

**Comment by Illya-Lykhachov** [comment]
<Button ..., CheckReadOnly=True}"/>
В таком режиме кнопка видится активной, но при нажатии ничего не происходит (команда не выполняется)

**Comment by Illya-Lykhachov** [comment]
Для документов:
<Button >
  <Button.DropDown>
     <DropDownMegaMenu >
        <MenuItem ..., CheckReadOnly=True}"/>
     </DropDownMegaMenu>
     </Button.DropDown>
</Button>
В таком режиме вообще никак не учитывается CheckReadOnly, документ спокойно создаётся (команда MenuItem выполняется)

**Comment by alex-kukhtin** [comment]
Fixed in 7316
