### ISSUE TITLE
DoubleClick в Popover

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#133]
Если в строке индекса есть popover, а в родительской таблице для DoubleClick назначена команда, то она выполняется при двойном клике в любом месте окна popover'а
Пример - список объектов учёта с всплывающими ценами. в поповере есть флажек "Показать историю". Попереключай его быстро.

**Comment by alex-kukhtin** [comment]
Fixed in 7312
