### ISSUE TITLE
Конфликт CheckReadOnly и Disabled

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#137]
Если база в режиме Readonly, в контроле есть и CheckReadOnly, и Disabled, то Disable "работает с преимуществом". Т.е. кнопка отображается активной при Disabled=false не смотря на ReadOnly=true.
Пример в приказе о приёме на работу.
Command="{..., CheckReadOnly=True}" Disabled="{Bind !Document.$canDelete}"

**Comment by alex-kukhtin** [comment]
И это правильно. Так и задумано.
Проверь свой Document.$canDelete
