### ISSUE TITLE
Не хватает иконок для персонала

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#138]
Примеры:
[https://fontawesome.com/icons/address-card?style=regular](url)
[https://fontawesome.com/icons/address-book?style=regular](url)
[https://fontawesome.com/icons/file-user?style=regular](url)
[https://fontawesome.com/icons/users?style=regular](url)
[https://fontawesome.com/icons/user?style=regular](url)
[https://fontawesome.com/icons/user-plus?style=regular](url)
[https://fontawesome.com/icons/user-minus?style=regular](url)
[https://fontawesome.com/icons/users-class?style=regular](url)
[https://fontawesome.com/icons/users-cog?style=regular](url)
[https://fontawesome.com/icons/user-clock?style=regular](url)
Коллекция:
[https://fontawesome.com/icons?d=gallery&c=users-people](url)

**Comment by alex-kukhtin** [comment]
А чем тебе не нравятся текущие user/users?
Остальные добавлю

**Comment by alex-kukhtin** [comment]
Осталось class, cog, clock.
user-plus/user-minus добавил в 7336
