### ISSUE TITLE
Wokrflow. Activity TrackRecord

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#139]
Самостоятельный элемент, а не только свойство request'ов

**Comment by Illya-Lykhachov** [comment]
Выход из реквеста с OK или CANCEL. Далее условие по OK продолжает процесс, по CANCEL заканчивает его. Нужно сделать запись в протокол об отмене процесса в реквесте.

**Comment by Illya-Lykhachov** [comment]
и setstate

**Comment by alex-kukhtin** [comment]
Done in 7352
