### ISSUE TITLE
sonata.isInstalled(); при отсутствии агента

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#142]
В консоли:
OPTIONS http://127.0.0.1:64031/revision net::ERR_CONNECTION_REFUSED
Uncaught (in promise) false

`
	if (!rep.$isNew) {
		root.XML = rep.SavedData;
		root.$$hasSonata = await cmn.hasSonata();
		initProperties(root.XML.DECLARBODY);
		return;
	}
`

В этом случае выполнение останавливается на вызове cmn.hasSonata();

**Comment by alex-kukhtin** [comment]
Fixed in 7384
