### ISSUE TITLE
Index.Export

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#145]
`
"actions": {
		"index": {
			"index": true,
			"parameters": { "Menu": "Purchase" },
			"template": "index.template",
			"view": "index.view",
			"export": {
				"format": "xlsx",
				"template": "index.template",
				"fileName": "@[RegisterOfDocuments]"
			}
		}
	}
`
 В ХП не передеается параметр Menu.

**Comment by alex-kukhtin** [comment]
Fixed in 7424
