### ISSUE TITLE
ХП .Index.Export

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#147]
Не передаются параметры, которые передаются в основной Index. К примеру: @Offset, @PageSize, @Order, @Operation, @Fragment.

**Comment by alex-kukhtin** [comment]
Наверное это правильно? Нафига экспортировать страницы по одной?

**Comment by AlexeyTishkin** [comment]
Дело не в страницах, а в фильтрах. Список операций отфильтровали по реализации за текущий месяц. А в экспорт попали все операции из "Продажи" за весь период.

**Comment by alex-kukhtin** [comment]
Наверное ты прав.
Только надо будет везде пересмотреть процедуры экспорта.
Ну а страницы не будешь использовать :-)

**Comment by AlexeyTishkin** [comment]
> Только надо будет везде пересмотреть процедуры экспорта.

Хорошо.

> Ну а страницы не будешь использовать :-)

Да. Параметр пусть передается, а использовать по усмотрению.

**Comment by alex-kukhtin** [comment]
7566. Сделано не так. Теперь можно передавать Argument в команду Export.
