### ISSUE TITLE
Экспорт в XML

### ISSUE THREAD

**Issue by nik-man** [alex-kukhtin/A2v10#148]
В схеме:

```
			<xs:choice>
				<xs:element name="H07" type="DGchk"/>
				<xs:sequence>
					<xs:element name="HLIQ" type="DGchk"/>
					<xs:element name="R001G1D" type="DGDate"/>
				</xs:sequence>
			</xs:choice>
```

В модели:

```
        "H07": false,
        "HLIQ": true,
        "R001G1D": "16012019",
```

В файле XML теги H07, HLIQ и R001G1D отсутствуют вовсе.
Возможно, такая конструкция непредусмотрена.

Пример в тестовой базе:
http://dev.a2start.com/fiscal_report/f0100110/edit/12805
Можно попытаться выгрузить в XML -- выдаст ошибку.

**Comment by alex-kukhtin** [comment]
Fixed in 7425
