### ISSUE TITLE
DoubleClick в списках

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#149]
Для удаления элемента списка нужно сделать 2 клика: выделить и удалить. Если сделать это быстро, то срабатывает событие doubleclick и элемент открывается. При этом и нажатие на удалить срабатывает. Получаем подтверждение на удаление после открытия (удаляем, но элемент остаётся открытым, так как удаление было в предыдущем контексте)

**Comment by alex-kukhtin** [comment]
Не могу повторить. Если есть реальный кейс, делай новый issue.
