### ISSUE TITLE
Отображение года

### ISSUE THREAD

**Issue by shevchuk-vadim** [alex-kukhtin/A2v10#151]
Если год - числовое необязательное поле, и поставить DataType=Number, HideZeros=True, то тогда он отображается в виде "2 018", с разделителем тысяч. А нужно "2018" без разделителя.

**Comment by alex-kukhtin** [comment]
Done (7438)
DataType = Number, Format = '0000'
Формат:  #,##00.00## - 
  # - необязательная цифра,
 0  - обязательная цифра
 '.' - десятичная точка
 ',' - разделитель тысяч
