### ISSUE TITLE
Ввод целого числа

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#157]
<TextBox Value="{Bind XML.DECLARBODY.R0207G3, DataType=Number}"/>
Необходимо ограничить ввод целым числом (в т.ч. отрицательным).
В схеме:

<xs:simpleType name="DGdecimal0">
    <xs:restriction base="xs:decimal">
      <xs:pattern value="\-{0,1}[0-9]+(\.0{1,2}){0,1}"/>
    </xs:restriction>
  </xs:simpleType>

**Comment by alex-kukhtin** [comment]
Done (7438)

**Comment by alex-kukhtin** [comment]
Number = "True". Разрешил вводить минус
