### ISSUE TITLE
Странное поведение DatePicker

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#162]
![image](https://user-images.githubusercontent.com/35328100/55728504-db84ac00-5a1c-11e9-86e5-77e1ee43ea21.png)
Выбираем следующий месяц (один клик, руки не дрожат, повторяется даже у женщин) и он перескакивает через один. Наблюдается **только** если у предыдущего периода (который меняли) был установлен последний день (если хоть на день меньше - всё в порядке) и если в следующем периоде на один день меньше, - с 31 марта скачет на 1 мая, а с 30 апреля на 30 мая (прибавляет столько дней, сколько в предыдущем месяце?).

**Comment by alex-kukhtin** [comment]
Fixed in 7528
