### ISSUE TITLE
Платформа не распознает вложенный объект (при сохранении), если у него свойство Id с маленькой буквы (id)

### ISSUE THREAD

**Issue by nik-man** [alex-kukhtin/A2v10#163]
Два вложенных объекта: client и coach. Все абсолютно идентично.
Идентификатор сущности "Id" в обоих случаях одинаковый.
client.Id распознается
coach.id -- нет.

![object_id](https://user-images.githubusercontent.com/35918141/55736499-1a6e2e00-5a2c-11e9-9631-b96f63df2db0.png)

**Comment by alex-kukhtin** [comment]
Подумал, так и оставлю. Там куча предопределенных имен и все они с большой буквы.
Так что так и останется.
