### ISSUE TITLE
ComboBox

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#169]
`<ComboBox Value="{Bind Parent.Filter.BankAccount}" ItemsSource="{BankAccounts}"><ComboBoxItem Value="{Bind Id}" Content="{Bind Name}"/>/ComboBox>`

Если значения Parent.Filter.BankAccount и BankAccounts типа bigint, то при обновлении страницы (либо переходе по ссылке) не отображается наименование выбранного элемента.

Для повторения:
[Платежи](http://dev.a2start.com/accounting/bank)
Выбрать счет, F5.

Если поменять типы на nvarchar - все работает.

**Comment by alex-kukhtin** [comment]
Уже починил. Не помню когда
