### ISSUE TITLE
ts $stateReadOnly нет в описании типа

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#173]
'TRoot.$IsCreateDocumentDisabled'(this: TRoot) { return this.$stateReadOnly || !this.Permit.CanEdit; },
Ошибка	TS2339	(TS) Свойство "$stateReadOnly" не существует в типе "TRoot".

**Comment by alex-kukhtin** [comment]
Есть там оно.
Наверное забыл
export interface TRoot extends IRoot
скорее всего у тебя extends IElement
