### ISSUE TITLE
Странное поведение покраснения

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#174]
![image](https://user-images.githubusercontent.com/35328100/64964892-acfcde00-d8a4-11e9-8a54-d11ed1c1d34d.png)

TextBox или Static и DataType=Number. Если нет дробной части и разделителя, то краснеет не смотря на отсутствие NegativeRed

**Comment by alex-kukhtin** [comment]
Не могу повторить. Где это?

**Comment by Illya-Lykhachov** [comment]
Уже и я не повторю. Этой редакции формы уже нет
