### ISSUE TITLE
В LazzyArray не добавляются элементы

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#176]
Command="{BindCmd Dialog, Action=Append, Argument={Bind Agents.Selected(AccountingPoints)}, Url='/Catalog/AccountingPoint/Edit'}"

После выбора в диалоге элемента, массив AccountingPoints остаётся пустой

**Comment by alex-kukhtin** [comment]
Так и будет. Это связано не с диалогом, а с выбранным элементом.
Аргумент формируется в момент формирования команды. А потом Selected 
Надо переделать на Execute.
