### ISSUE TITLE
ListItem с If

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#177]
`<ListItem Icon="Table" Header="@[SheetSettlementsPartners]" Content="@[ShowTurnoverSheet]"
									  If="{Bind Accounts.$selected.$UseAgent}"
									  Command="{BindCmd Open, Url='/reports/agents/turnoverSheetAgent',
												Argument={Bind Accounts.$selected.$ReportArgument}, NewWindow=True}"/>`

В списке на экране не отображается, но место резервируется.

**Comment by alex-kukhtin** [comment]
v 7568
