### ISSUE TITLE
При DataType=Period или Number HideZeros=True не работает

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#178]

**Comment by alex-kukhtin** [comment]
Не могу повторить. Покажи.

**Comment by Illya-Lykhachov** [comment]
Любой документ выплаты зарплаты, проводки, закладка зарплата. ShowTransactions.dialog.xaml
![image](https://user-images.githubusercontent.com/35328100/67262499-b124a880-f4ad-11e9-872e-43dc925a5f1d.png)
С DataType=Number проблем нет.
Там же, если период непустой (любой документ начисления зарплаты), период отображает год и месяц слитно.
