### ISSUE TITLE
Обработка файлов для импорта из клиент-банка

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#179]
В файле две колонки с номером р/с: RR_DB, IBAN_DB. Предпочтительней использовать данные из IBAN_DB, но в ней нет значений по некоторым строкам. Нужна возможность взять значение из другого поля в случае, если в текущем пусто: isnull(IBAN_DB, RR_DB).

**Comment by alex-kukhtin** [comment]
Сделано в 7566.
