### ISSUE TITLE
$invoke - передача в процедуру числа в виде String

### ISSUE THREAD

**Issue by ViriaskinOM** [alex-kukhtin/A2v10#180]
отрабатываю запись в sql-процедуре SaveCoordinate,
в ней параметры
	@UserId bigint,
	@Id bigint,
	@Lat nvarchar(255),
	@Lng nvarchar(255)
Значения lat и lng 
latlng: 52.419740213287476; 13.409581519229391
await vm.$invoke('SaveCoordinate', { 'Id': Tre.TreeId, 'Lat': lat, 'Lng': lng}, '/savetrees/doctrees/');

в процедуре получаю обрезанные до 4-го знака числа:
 52.4197
13.4096
решил вот так:
await vm.$invoke('SaveCoordinate', { 'Id': Tre.TreeId, 'Lat': lat.toString(), 'Lng': lng.toString() }, '/savetrees/doctrees/');

**Comment by alex-kukhtin** [comment]
v 7568
