### ISSUE TITLE
Расположение автосписка селектора

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#188]
![image](https://user-images.githubusercontent.com/35917940/68688970-5a743100-0578-11ea-98d2-5db9868fcab8.png)

Сделать возможность расположения автолиста поверх панели. Например, как для комбобокса:
![image](https://user-images.githubusercontent.com/35917940/68689070-81326780-0578-11ea-8fb0-28892bf7541f.png)

Увидеть можно:
http://dev.a2start.com/accounting/bank
Створити платіж - Платіж до бюджету - Операція: Перерахування інших податків - в такспаде селектор "Податок".

**Comment by alex-kukhtin** [comment]
Done in 7586
