### ISSUE TITLE
Static. Разметка

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#195]
`<Static Value="{Bind VATRate.Code}" ValidateValue="{Bind VATRate}" Wrap="NoWrap" Align="Right"
								TestId="VATRate"/>`

[Придбання](http://dev.a2start.com/purchase/operations2) - Створити документ - Податкова накладна - Таблица с ТМЦ - Колонка 8 "Код ставки"
![image](https://user-images.githubusercontent.com/35917940/71104819-17cff500-21c5-11ea-9f2d-0dd4e4179cb2.png)

При наличии значения все ок.
![image](https://user-images.githubusercontent.com/35917940/71104877-30d8a600-21c5-11ea-9e27-d939b055b3a9.png)

**Comment by alex-kukhtin** [comment]
v 7604
