### ISSUE TITLE
Проблема с отправкой сообщений в workflow

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#199]
Inbox на роль, в которой группа и пользователь. Сообщение отправляется только первому пользователю из группы, а остальным нет.

**Comment by alex-kukhtin** [comment]
Done (7622)
Нужно возвращать список адресов из хранимой процедуры и связывать с полем через обращение к модели данных. Например 
```xml
To=" {{Message.Addresses}}"
