### ISSUE TITLE
Отчетность в формате Excel

### ISSUE THREAD

**Issue by IgorAIvanov** [alex-kukhtin/A2v10#201]
Реализовать возможность сохранение в базе данных сформированных на сервере отчетов (без передачи на клиента) так как это реализована для отчетности Stimulsoft.
"attachReport": {
      "type": "clr",
      "clrType": "clr-type:A2v10.Reports.Actions.AttachStiReport;assembly=A2v10.Reports",
      "async": true,
      "parameters": {
        "Report": "savetrees/applicants/emptyresponse",
        "Model": "ReqApplicants.emptyresponse",
        "Schema": "kv"
      }
    }

**Comment by alex-kukhtin** [comment]
Done (7631)

```javascript
commands: {
  "attachReportXlsx": {
     "type": "clr",
	"clrType": "clr-type:A2v10.Reports.Actions.AttachXlsxReport;assembly=A2v10.Reports",
	"async": true,
	"parameters": {
	   "Report": "sales/waybill/waybill",
	    "Model": "Document",
	    "Schema": "a2demo"
	}
   }
}
