### ISSUE TITLE
workflow. StartProcess

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#204]
Для дочерноего процесса нужно:
 - наследовать владельца
 - добавит свойство Parent в a2workflow.Processes (не только для связи самих процессов, но и для связи их моделей)

**Comment by alex-kukhtin** [comment]
Done (in 7631)

**Comment by alex-kukhtin** [comment]
Не забудь запустить a2v10workflow.sql!
