### ISSUE TITLE
Восстановление пароля. Нет хранимой процедуры

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#205]
account/forgotpassword
нажимаем на "Отправить ссылку"
The stored procedure 'a2messaging.WriteLog' doesn't exist.

**Comment by alex-kukhtin** [comment]
Запусти скрипт a2messaging.sql

**Comment by Illya-Lykhachov** [comment]
Вот такое письмл приходит:

![image](https://user-images.githubusercontent.com/35328100/74503421-81d0f600-4ef9-11ea-8844-2a439073a15a.png)

**Comment by alex-kukhtin** [comment]
Как всегда при @ это означает, что это ключ словаря....
