### ISSUE TITLE
Аворизация в системе не только по EMail

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#206]
account/login
Для корпоративных решений нужна возможность авторизации по логину. Можно разрулить параметром приложения в web.config

**Comment by alex-kukhtin** [comment]
Что это? Нафига усложнять?

**Comment by Illya-Lykhachov** [comment]
Чтобы подклчить решение на А2 к существующей системе, в которой уже есть пользователи с обычными логинами

**Comment by alex-kukhtin** [comment]
Done
