### ISSUE TITLE
Проблема с FieldSet

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#208]
`<FieldSet Orientation="Vertical">`
`  <TextBox .../>`
`  <StackPanel Orientation="Horizontal">`
`    <TextBox .../>`
`    <TextBox .../>`
`  </StackPanel>`
`</FieldSet>`

Два textbox внутри stackpanel отображаются один над другим не взирая на указанную ориентацию.
Меняю TextBox на Button - проблемы нет, батоны выстраиваются горизонтально

**Comment by alex-kukhtin** [comment]
Done 7675
