### ISSUE TITLE
Добавить в заголовок формируемого ХТМЛ коммент о платформе

### ISSUE THREAD

**Issue by AndriyNesterenya** [alex-kukhtin/A2v10#210]
Добавить в заголовок формируемого ХТМЛ коммент в стиле
/*
 * Based on A2v10 platform by Alex Kukhtin
 * GitHub : https://github.com/alex-kukhtin/A2v10
 */
или что мы хотим сказать любопытствующему кулхацкеру в целях популяризации платформы и формирования сообщества

**Comment by alex-kukhtin** [comment]
Сделал. Будет в версии 7713
