### ISSUE TITLE
workflow не поднимает процесс с AutoStart=1

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#225]
Александр Кухтин, [16.06.20 08:59]
Пиши issue. Оно не работает. Там заглушка стоит.

Александр Кухтин, [16.06.20 08:59]
public static void AutoStart(Int64 processId, ILogger logger)
    {
      throw new NotImplementedException("AppWorkflow.AutoStart");
    }

**Comment by alex-kukhtin** [comment]
Done 7675
