### ISSUE TITLE
Нужна иконка TrashOutline

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#226]
Такая же как и Trash, но в белых линиях

**Comment by alex-kukhtin** [comment]
Блин. Ну в каких белых?
![image](https://user-images.githubusercontent.com/26379138/85017667-8aba2880-b174-11ea-927c-572c8da143ba.png)

А это в каких?

**Comment by Illya-Lykhachov** [comment]
![image](https://user-images.githubusercontent.com/35328100/85017847-d5d43b80-b174-11ea-8bff-493e4490acfa.png)

**Comment by alex-kukhtin** [comment]
Ну так и пиши. Красный цвет просто надо убрать.
Украшательствами занимаетесь.....

**Comment by Illya-Lykhachov** [comment]
Я так и написал: как все иконки типа *Outline

**Comment by alex-kukhtin** [comment]
Нет. Outline это контур, а не цвет.
![image](https://user-images.githubusercontent.com/26379138/85019320-4b410b80-b177-11ea-918c-c589477d0539.png)

**Comment by Illya-Lykhachov** [comment]
Тебе видней. Главное - ты понял что нужно

**Comment by alex-kukhtin** [comment]
Done 7675
