### ISSUE TITLE
Установка для элемента списка свойства padding никак не влияет на отображение. 

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#227]

**Comment by Illya-Lykhachov** [comment]
В коде: <ListItem Padding="1">
Отображается:
![Annotation 2020-06-21 094115](https://user-images.githubusercontent.com/35328100/85218525-fa622a80-b3a3-11ea-9325-c1a263f55644.jpg)

**Comment by alex-kukhtin** [comment]
Padding ставится не для этого элемента (.a2-list-item), а для внутреннего (.generic-list-item).
Так надо.
