### ISSUE TITLE
Нужно сделать AfterSave для синхронизации объектов между базами в мультитенанте

### ISSUE THREAD

**Issue by ViriaskinOM** [alex-kukhtin/A2v10#228]
Нужно сделать AfterSave для синхронизации объектов между базами в мультитенанте
Когда модель сохраняется (вызывается sql-процедура ModelName.Update) после этого нужен вызов AfterSave с передачей в него объекта модели
Желательно универсальное решение, чтобы любую модель можно было настроить и получить запуск AfterSave после выполнения Update

**Comment by alex-kukhtin** [comment]
Done. Version 7677.
