### ISSUE TITLE
Экспорт данных отчётов в файлы (интеграция с другими приложениями)

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#234]
В общем виде нужно построить понятный пользователю отчёт для визуальной верификации, а затем сделать импорт данных (без шапки и подвала) в табличный файл указанного типа. Чаще всего dbf или csv.
Идея с mapping модели (указаного массива) в поля табличного файла (как в клиент-банке, только в обратном направлении) кажется интересной.

**Comment by alex-kukhtin** [comment]
Done (7712)
