### ISSUE TITLE
Для атрибута Wrap добавить значение, позволяющее разрывать строку только по /n и не разрывать слова

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#235]
Например, в ячейке таблицы с **Width="Fit"** для строки "<слово1>\n<слово2>\n<слово3>" должно быть
<слово1>
<слово2>
<слово3>
сейчас для строки "Р12\nРН5\nРВ4\n" получается:
![image](https://user-images.githubusercontent.com/35328100/95419558-86439680-0942-11eb-8c82-3712d2bf1465.png)
С Width="Auto" такой проблемы нет, но несколько колонок с автошириной в одной таблице выглядят криво

**Comment by alex-kukhtin** [comment]
А чем Wrap="PreWrap" не нравится?

**Comment by Illya-Lykhachov** [comment]
Тем, что ничего не меняется
![image](https://user-images.githubusercontent.com/35328100/95705286-1db72b00-0c5c-11eb-8eab-7dcb16febce9.png)
