### ISSUE TITLE
Перестала работать команда SaveAndClose в диалогах

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#237]
Сохранение происходит, а диалог не закрывается
`<Dialog.Buttons>
	<Button Content="@[SaveAndClose]" Command="{BindCmd SaveAndClose, ValidRequired=True}" Style="Primary"/>
...
</Dialog.Buttons>
`

**Comment by alex-kukhtin** [comment]
А вот повторить не получается.
У тебя там случайно не написано
$save()
$close()?

Надо:

await $save();
$close()

**Comment by IgorAIvanov** [comment]
Подтверждаю наличие проблемы у метода $modalSaveAndClose
Диалоговое окно перестало закрываться.
Пришлось заменить на
  await $save();
 $modalClose(retValue);

**Comment by Illya-Lykhachov** [comment]
> А вот повторить не получается.
> У тебя там случайно не написано
> $save()
> $close()?
> 
> Надо:
> 
> await $save();
> $close()

Использую только команду SaveAndClose в разметке (Command="{BindCmd SaveAndClose}")

**Comment by alex-kukhtin** [comment]
Done (7745)
