### ISSUE TITLE
Погрешность с высотой строк таблицы

### ISSUE THREAD

**Issue by Illya-Lykhachov** [alex-kukhtin/A2v10#248]
![image](https://user-images.githubusercontent.com/35328100/120920493-c1f85100-c6c7-11eb-9246-c373abf03d0d.png)
Если левая ячейка имеет rowspan>0 и wrap=true (ширина колонки Fit), то высота всей строки увеличивается из-за её содержимого

**Comment by alex-kukhtin** [comment]
И что тут не так?

**Comment by Illya-Lykhachov** [comment]
Высота первой строки больше остальных

**Comment by alex-kukhtin** [comment]
Html это не excel. Сделай это в html.
