### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by kharkovchanin59** [alex-kukhtin/A2v10#263]
Добрый день. Попытался применить обновление, но после этого вываливается ошибка при запуске
[Server Error in.docx](https://github.com/alex-kukhtin/A2v10/files/9546474/Server.Error.in.docx)
после первой попытки я снес студию, установил все по новой. все работало, еще раз попытался обновить - та же ситуация. Сообщение в файле

**Comment by alex-kukhtin** [comment]
Когда появляются такие ошибки - 99.9999% что нужно обновить assemblyBinding в web.config.
Правильные значения всегда (ну почти :-) ) лежат в web.config.sample
