### ISSUE TITLE
components\collectionview.js sourceCount()  всегда возвращает полную длину коллекции, не учитывает что может быть наложен фильтр

### ISSUE THREAD

**Issue by PavelVir** [alex-kukhtin/A2v10#264]
// client collection
Vue.component('collection-view', {

метод 
sourceCount() {
				return this.ItemsSource.length; -- > возвращает длину, не учитывая возможно наложенный фильтр

вариант решения: 
				return this.filteredCount; 

Сценарий тестирования:

Дано:
 любой  CollectionView  RunAt="Client" PageSize=''5' с  FilterDelegate="filter"
коллекция на 2+ страницы

1. Устанавливаем значение фильтра
2. Pager Source="{Bind Parent.Pager}"  - всё равно показывает все страницы, вместо отфильтрованных.

**Comment by alex-kukhtin** [comment]
Исправлено в версии 7901
