### ISSUE TITLE
Сделать, чтобы при перелистывании месяцев не закрывался Date Picker

### ISSUE THREAD

**Issue by Sunapi** [alex-kukhtin/A2v10#266]
Сделать, чтобы при перелистывании месяцев самостоятельно не закрывался Date Picker для поля выбора одной даты

**Comment by alex-kukhtin** [comment]
Так вроде ж не закрывается.

**Comment by Sunapi** [comment]
Вот видео. Постоянно прячется:

https://github.com/alex-kukhtin/A2v10/assets/49755634/3322e8d9-004a-40e7-aff6-bebeb38ade21

**Comment by Lion-killer** [comment]
> Вот видео. Постоянно прячется:
> 
>  msedge_oNPZYnhWXy.mp4

Можливо з цим полем пов'язані якісь дані. Спробуйте повідключати по черзі всі з'вязані поля та події

**Comment by alex-kukhtin** [comment]
Done
