### ISSUE TITLE
Розмітка дочірніх елементів в TabPanel

### ISSUE THREAD

**Issue by Lion-killer** [alex-kukhtin/A2v10#267]
![image](https://user-images.githubusercontent.com/22013083/220129181-ad9ed45b-1f10-4e2e-ac77-6a2065666b77.png)

При такому налаштуванні TabPanel в контейнері Page система веде себе як очікується: тобто полоса прокручування з'являється на елементі Table. У контейнері Dialog полоса прокручування з'являється на контейнері вцілому.

**Comment by alex-kukhtin** [comment]
Done. (7935)
