### ISSUE TITLE
Покращення юзабіліті Selector

### ISSUE THREAD

**Issue by Lion-killer** [alex-kukhtin/A2v10#270]
При вводі тексту в Selector, має автоматично виділятися перший знайдений елемент, щоб в будь-який момент часу при натисненні Enter відбувся вибір елементу.

Реалізації на прикладі 1С Підприємство:

https://user-images.githubusercontent.com/22013083/226177197-b70620db-5445-41f0-b579-15f85942ac6d.mp4

Таким чином: 

- для вибору "Контрагент 1" достатньо натиснути "к + Enter"
- для вибору "Контрагент 2" - натиснути "к+стрілка вниз+Enter"
- для виробу "Роги та копита" - натиснути "р+Enter"

**Comment by alex-kukhtin** [comment]
Done (7923)
