### ISSUE TITLE
Властивість FetchData в компоненті Selector та SelectorSimple

### ISSUE THREAD

**Issue by Lion-killer** [alex-kukhtin/A2v10#271]
<SelectorSimple FetchData="{Bind Document.$AgentFetchData}" Url="/catalog/agent" Value="{Bind Document.Agent}" />

Відбір працює тільки в Fetch, при виборі через Browse для SQL процедури відбір не встановлюється

**Comment by alex-kukhtin** [comment]
В Selector і не має працювати. Там же Browse окремою командою.
В SelectorSimple - виправлено.
