### ISSUE TITLE
Параметр Data в команді File

### ISSUE THREAD

**Issue by Lion-killer** [alex-kukhtin/A2v10#277]
При використанні команди File. параметр Data - ігнорується.

Приклад:

XAML

        <Button Command="{BindCmd   Command=File, 
                                    FileAction=Download, 
                                    Argument={Bind Root.$ObjectId}, 
                                    Data={Bind Root.$Params}, 
                                    FileName=temp, Url=/print/TemplateReport/}" 
                Content="Зберегти як файл (File)" />

TS

const template: Template = {
    properties: {
        'TRoot.$ObjectId'() { return this.__baseQuery__.ObjectId },
        'TRoot.$Params'() {
            return { modelName: this.__baseQuery__.modelName, templateName: this.__baseQuery__.templateName }
        }
};

Результуючий URL: https://localhost:44398/_file/print/TemplateReport/1?export=1

**Comment by alex-kukhtin** [comment]
Done (7947)
