### ISSUE TITLE
Не спрацьовує асинхронний валідатор

### ISSUE THREAD

**Issue by Lion-killer** [alex-kukhtin/A2v10#282]
При програмному встановленні атрибутів спрацьовують лише звичайні валідатори, асинхронний спрацьовує тільки після редагування поля.
![image](https://github.com/alex-kukhtin/A2v10/assets/22013083/ad52bb3c-920e-4548-89ee-765e7117aed5)

**Comment by alex-kukhtin** [comment]
Done (version 7951)
