### ISSUE TITLE
NameMaxChars у PropertyGrid

### ISSUE THREAD

**Issue by Wdivin** [alex-kukhtin/A2v10#284]
![image](https://github.com/alex-kukhtin/A2v10/assets/87857733/14e0a8bd-2eea-437e-84f9-f8d5e39cbe67)
![image](https://github.com/alex-kukhtin/A2v10/assets/87857733/72e196e8-37a4-489f-86f1-e6f19ce6c9d8)

Якесь непорозуміння із властивістю NameMaxChars у PropertyGrid. При спробі встановити замість імені властивості стає значення.

**Comment by Wdivin** [comment]
Framework версия 10.0.7950.0
При выводе PropertyGrid без NameMaxChars выводит корректно, а если установить NameMaxChars, то вместо имени свойства выводит его значение. на скрине 2 идентичных PropertyGrid, только в левом установлено NameMaxChars, а в правом нет. Правый отображается нормально, а в левом и в Name и в Content выводит Content. я ж там вроде даже пулреквест запилил

**Comment by Wdivin** [comment]
https://github.com/alex-kukhtin/A2v10/pull/285 воть...

**Comment by alex-kukhtin** [comment]
Действительно. Туплю в последнее время. Спасибо!
Но в 7951 уже не успел.

**Comment by alex-kukhtin** [comment]
Странно, но в Core версии этой ошибки нету :-(

**Comment by alex-kukhtin** [comment]
Done (version 7952)
