### ISSUE TITLE
Валідація моделі при збереженні

### ISSUE THREAD

**Issue by Lion-killer** [alex-kukhtin/A2v10#286]
Додати валідацію моделі при виклику $saveModified():
![image](https://github.com/alex-kukhtin/A2v10/assets/22013083/611c209e-6bab-4228-b08d-00ac63e962da)
Наразі при натисненні кнопки "Зберегти" можливе збереження невалідної моделі

**Comment by bohdan-bats-bs** [comment]
Пропоную в функції `IController.$save` брати `validRequired="true"`, якщо цей параметр не є заданий, оскільки це більш частий сценарій

**Comment by alex-kukhtin** [comment]
> Пропоную в функції `IController.$save` брати `validRequired="true"`, якщо цей параметр не є заданий, оскільки це більш частий сценарій

Ні. Це не доречно. І поламає кучу вже написаного кода.

**Comment by alex-kukhtin** [comment]
Done. v 7959
