### ISSUE TITLE
Конфликт ContextMenu и Hyperlink в DataGrid

### ISSUE THREAD

**Issue by Wdivin** [alex-kukhtin/A2v10#290]
коли у datagrid визначено ContextMenu та є елемент Hyperlink, то при ПКМ по гіперлінку і гіперлінк спрацьовує і контекстне меню відкривається.

**Comment by Wdivin** [comment]
Тут мне кажется лучше отключить срабатывание гиперссылки по ПКМ

**Comment by alex-kukhtin** [comment]
Done (7955)
