### ISSUE TITLE
Grid.VAlign не работает

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#39]
`<TableRow><Header Grid.VAlign="Middle">@[Invoice] №</Header>`

**Comment by alex-kukhtin** [comment]
А почему это вдруг должно работать? Это же TableRow.
Там нужно так:
```xml
<TableRow>
  <TableCell VAlign="Middle">
    <Header>...
```

Grid.VAlign будет работать только в элементах, которые НЕПОСРЕДСТВЕННО вложены в Grid.
Полная аналогия Grid.Row, Grid.Col.
