### ISSUE TITLE
Не возвращается Id документа в строку браузера после сохранения

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#49]
Бухгалтерія - Банківські операціі - Нова - Оплата постачальнику. При создании: http://localhost:81/document/payment_order_out/edit/new?Operation=BAPS.  Меняем номер - сохраняем. В строке: http://localhost:81/document/payment_order_out/edit/new?Operation=BAPS.

**Comment by alex-kukhtin** [comment]
Fixed in 7155
