### ISSUE TITLE
При определении команд не работает передача параметров.

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#50]
model.json:
`"commands": {
		"createCashPayment": {
			"type": "sql",
			"parameters": { "Kind" : "CWOT", "Operation": "CCPS" },
			"procedure": "InvoiceIn.CreatePayment"
		}`
В ХП не передаются параметры Kind, Operation.

**Comment by alex-kukhtin** [comment]
Fixed in 7155
