### ISSUE TITLE
BindCmd DbRemove

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#51]
Объекты учета - Определенный объект - Открыть - Операции - Определенная операция - Удалить. Команда: `Command="{BindCmd DbRemove, Argument={Bind}, Confirm='@[Sure.Delete]'}"`.
Вызывается ХП [a2].[Entity.Delete].

**Comment by alex-kukhtin** [comment]
Fixed in 7155
