### ISSUE TITLE
Command="{BindCmd Open

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#67]
Не получилось передать параметры в ХП при помощи аргумента Data. Command="{BindCmd Open, Url='{Bind Root.Header.DetailsUrl}', Argument={Bind}, Data={Bind Root.$detailsParams}, NewWindow=True}"
Пример: http://http://dev.a2start.com/reports/agents/turnoversheetagent361/new При открытии детализирующего отчета.

**Comment by alex-kukhtin** [comment]
Не поддерживается. Нужно использовать объектный аргумент и вычисляемое свойство.
