### ISSUE TITLE
В селекторе не работает Hyperlink с атрибутом If и DropDownMenu

### ISSUE THREAD

**Issue by shevchuk-vadim** [alex-kukhtin/A2v10#69]
1. Открыть свойства существующего договора.
2. Очистить контрагента.
3. Выбрать контрагента.
Меню по клику на на трех точках перестает открываться.

**Comment by alex-kukhtin** [comment]
Fixed in 7177

**Comment by shevchuk-vadim** [comment]
Если в п. 3 выбор произвести через fetch, то проблема осталась.

**Comment by alex-kukhtin** [comment]
Fixed again in 7192
