### ISSUE TITLE
Работа с картинками: внешний и серверный источники данных

### ISSUE THREAD

**Issue by alex-wi** [alex-kukhtin/A2v10#71]
если мы делаем тег коллекции картинок, то у нас появлется инструмент добавления картинки из внешнего источника (компа пользователя, иконка пустая). мы к сожалению не можем его использовать для открытия диалогового окна с выбором картинок с локального источника.
Коллекция рендерится так как надо, и если сделать возможность переключения источника, то мы могли бы указывать диалог отвечающий за вызов какого-то набора картинок.
Варианты реализации. например sourcetype=server/user.  в случае сервера - иконка добавления элемента прячется и мы делаем свою кнопку вызова диалога с картинками/иконка добавления имеет в качестве параметра ссылку на диалог.
в случае значения типа источника - пользователь, мы работаем в обычном варианте.
параметр readonly трогать не стоит. он задает нормальное поведение контрола и переключает его между режимами редактирования и чистого вывода коллекции. и звучит и работает логично.
необходимо: при включенном параметре readonly прятать пустую иконку добавления, и в случае реализации параметра тип источника при попытке добавления картинки, необходимо выдавать сообщение, что включен параметр только для чтения.

**Comment by alex-kukhtin** [comment]
Нет. Так не будет. Всякие серверные источники делайте сами. В действительности, там всего-то и нужно правильный Id подставить. ReadOnly в <ImageList> подразумевает, что пользователь не может добавлять/удалять картинки в/из списка.
