### ISSUE TITLE
По стимулсофту: настройка лицензии и связка кодовой страницы с пользовательской

### ISSUE THREAD

**Issue by alex-wi** [alex-kukhtin/A2v10#73]
Очень нужна связка кодовой страницы в настройках стимулсофта с предпочтениями пользователя.
ПО умолчанию надо брать код из профиля. В дальнейшем при переключении языка на экране, язык текущей сессии должен заменять дефолтное значение.
сейчас прихдится перезатирать словари стимулсофта, чтобы обеспечить нужный язык.

Дефолтное значение или сам параметр отвечающий за номер лицензии в вебконфиге приводит к ошибке при выводе отчета. Отключение параметра возвращает все в рабочее, триальное состояние

**Comment by alex-kukhtin** [comment]
А у тебя есть правильный код лицензии? Если есть - напиши его туда. Если нет - то в чем вопрос?

**Comment by alex-kukhtin** [comment]
Динамическое переключение языка вообще планируется.
Ну то есть в профиле нет языка. Он есть в web.config.

**Comment by alex-kukhtin** [comment]
Локализацию вьюера подправил в 7185
