### ISSUE TITLE
Создание механизма корневых шаблонов

### ISSUE THREAD

**Issue by alex-wi** [alex-kukhtin/A2v10#74]
Для обеспечения разработчиков возможностью контролировать набор элементов интерфейса на самом низком уровне и размещения элементов генерируемых в main.js в нужном месте и с нужным названием, необходим механизм привязки различных шаблонов к различным разделам сайта.
Программист прикладник должен контролировать все выводимые платформой сущности и форматировать их как ему требуется в задаче.
В данный момент можно только выбирать из типовых решений нужные и частично из изменять через стили. Переименование и прочие возможности не возможны без влезания в скрипт платформы. Думаю, что есть еще ряд преинсталлированных элементов в дллках, поведение которых также стоит рассмотреть в рамках этого вопроса.

**Comment by alex-kukhtin** [comment]
В main.js нету никаких шаблонов. Вот я нифига не понял, что ты хочешь?
