### ISSUE TITLE
Пользовательский словарь. Использование одинарной кавычки.

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#8]
"@Error.DuplicateArticle=Об'єкт з таким артикулом вже існує" приводит к "Uncaught SyntaxError: Unexpected identifier
    at main.js?v=7106:637
    at <anonymous>"

**Comment by alex-kukhtin** [comment]
В общем-то это не баг. Следить придется самим. Если есть кавычка, то константу нужно заключать в двойные кавычки
'TEntity.Article' : {msg: "@[Error]"}. Подстановка "в тупую". Нарушаются правила JS.
