### ISSUE TITLE
Не копипастится текст в поля с валидаторами - подчеркиваниями с клавы

### ISSUE THREAD

**Issue by AndriyNesterenya** [alex-kukhtin/A2v10#82]
Не удается скопипастить с клавы комбинациями Ctrl+Ins/Shift+Ins текст в поля, где присутствует валидатор со знакоместами-подчеркиваниями.
Как минимум в поля МФО/ЕДРПОУ в визарде создания банка и телефоны.

C мышки Копировать/Ввставить копипастится нормально

**Comment by alex-kukhtin** [comment]
Fixed in 7207
