### ISSUE TITLE
Формирование XML. Непонятное значение в файле.

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#94]
Розрахунок коригування сум податку на додану вартість (Д1) (F0200419). Тэг T2RXXXXG32. В модели такого свойства нет.

**Comment by AlexeyTishkin** [comment]
http://dev.a2start.com/fiscal_report/F0200419/edit/186

**Comment by alex-kukhtin** [comment]
Fixed in 7228
