### ISSUE TITLE
Формирование XML.

### ISSUE THREAD

**Issue by AlexeyTishkin** [alex-kukhtin/A2v10#98]
Если тип данных строка, значение "", а в схеме nillable="true", то в xml формировать не пустой тэг <T1RXXXXG08 ROWNUM="1"></T1RXXXXG08>, а с xsi:nil="true".

Пример: http://dev.a2start.com/fiscal_report/J0500105/edit/218. Сейчас ругается: The 'T1RXXXXG08' element is invalid - The value '' is invalid according to its datatype 'Oplg1DFColumn' - The Pattern constraint failed.

**Comment by alex-kukhtin** [comment]
Fixed in 7238
